### ISSUE TITLE
Uploading ks.cfg file with netcat unreliable

### ISSUE THREAD

**Issue by casr** [2creatives/vagrant-centos#13]
When Anaconda requests the file from the host system, it sends its HTTP headers requesting the file. Unfortunately, `nc` doesn't wait for the request to finish and often sends its payload before the end of the request leading to Anaconda waiting for input that's already been sent.

`nc` might be more reliable when used with `-i 2` or something similar although it does add a fair delay.

A workaround for now is to use the quick python web server with:

```
python -m SimpleHTTPServer 8080    # Python 2.x
python -m http.server 8080         # Python 3.x
```

which will serve the current directory and then can be referenced in the installer using the host's IP (usually 10.0.2.3) and the location of the file. Often that's http://10.0.2.3:8080/ks.cfg if you're in the same directory as the repo.

This is not ideal as it interrupts the whole automated nature of the process but it is more reliable for now.

**Comment by javornikolov** [comment]
Just to add a ref here too to the other project: https://github.com/opscode/bento and related the [Packer](http://www.packer.io/).
When I tried it, it managed to boot without manually asking for kickstart url.

Another approach could be NFS.

**Comment by pinepain** [comment]
There are already built-in TFTP in virtualbox, so why not just utilize it? At least, we have try.

**Comment by casr** [comment]
See the vagrant-centos/newserver branch for progress on this. It's a Ruby-based, will listen on 8081 (as before) and will quit after it's served `ks.cfg`. Unlike before, it will wait until Anaconda has finished requesting `ks.cfg`, i.e. until it receives a blank line on the TCP socket.

As this is primarily a tool for Vagrant, and Vagrant is Ruby-based, it makes sense to use this as the basis instead of Python. However, Ruby is installed in a custom location with Vagrant so rest of the work in this branch will need to find Vagrant's version of Ruby and use that instead of the system provided one.

I've pushed it for now in the hope that it's immediately helpful to someone.
