### ISSUE TITLE
add ability to ping by hostname

### ISSUE THREAD

**Issue by NicolasGeraud** [2creatives/vagrant-centos#14]
after a fresh "vagrant up", I'm not able to ping "vagrant-centos65.vagrantup.com".

Add this DN to the hosts resolve this.

Do you think this must be set in a fresh install ?

**Comment by casr** [comment]
Do you mean within the base box itself? I think this might be a bit confusing to set in the base box's host file because it won't be shared by other computers in the network.

What are you trying to do?

**Comment by NicolasGeraud** [comment]
After a vragrant up, I provision the VM with a tomcat based product (Liferay => www.liferay.com) which tried to resolve vagrant-centos65.vagrantup.com.
And I get an UnknownHostException.

So I put this in my Vagrantfile: 
config.vm.provision :shell, :inline => "echo '127.0.0.1    vagrant-centos65.vagrantup.com' >> /etc/hosts"

**Comment by casr** [comment]
> I think this might be a bit confusing to set in the base box's host file because it won't be shared by other computers in the network.

Well I checked what happened when setting the hostname with `config.vm.hostname` and it resulted in that value being added to the line beginning with 127.0.0.1 in `/etc/hosts`. In that regard, I'm going to assume that upstream has thought about this more and I'll add it in the next release. :)

For now though setting the hostname with `config.vm.hostname` might be a simpler way of achieving your goal.

Thanks for the report!

**Comment by casr** [comment]
Just to add, you'll need to make the hostname value something other than the original otherwise Vagrant will leave it untouched. For instance,

```
config.vm.hostname = "centos65.vagrantup.com"
```

should do the trick.
