### ISSUE TITLE
exclude=kernel* may lead to troubles in some cases

### ISSUE THREAD

**Issue by javornikolov** [2creatives/vagrant-centos#6]
I'm facing problem because of the custom configuration `exclude=kernel*`: it prevents [vagrant-vbguest](https://github.com/dotless-de/vagrant-vbguest) installing VirtualBox guest add-ons: because that attempts to install kernel-devel.

**Comment by casr** [comment]
Thanks for the report. I think it's beneficial having some kind of lock on the kernel version so that commands like `yum update` still work without any additional issues caused by not having VirtualBox Guest Additions. Having a blanket exclude on packages beginning with kernel might be a little extreme though.

I've done some initial tests on using yum-plugin-versionlock which seem to work as expected. I think I'll try and lock all packages related to the version of the kernel. I'll test out a full build and get back to you.

**Comment by javornikolov** [comment]
> so that commands like yum update still work without any additional issues caused by not having VirtualBox Guest Additions. 

One approach to deal with such scenarios is [vagrant-vbguest](https://github.com/dotless-de/vagrant-vbguest) plugin. (Which in addition aligns the addons with the relevant vbox version).

It depends on the context whether ability for kernel update would be desired or not - it's good to have control to change that. Main issue is to survive until the _provisioning stage_ (after that it's easier to tweak version pinning, etc).
And before _provisioning stage_ - what is affected I think are [vagrant plugins](https://docs.vagrantup.com/v2/plugins/index.html) only. If we want to influence these plugins (by pinning a package version): I can imagine that would need to be done via a vagrant plugin too. And for the sake of these scenarios - the question is what would be the best default inside the box image.

**Comment by casr** [comment]
@javornikolov have you been able to test this with vagrant-vbguest? I'm hoping new base box builds will be able to install kernel-devel to complete the installation now.

**Comment by javornikolov** [comment]
I tried to test it but since the newer VBox additions was already in: `vagrant-vbguest` just skipped the update.
(And there is some issue with `vagrant-vbguest` & manually uninstalled VBox additions).

Anyway - I tested how the new plugin is working in general: I believe it will work fine with `vagrant-vbguest`.

**Comment by casr** [comment]
Okay great. Happy to move to close?

**Comment by javornikolov** [comment]
:+1: I just manage to give it a try and it worked fine.

**Comment by casr** [comment]
Forgot to say; thanks for checking this out. Much appreciated!
