### ISSUE TITLE
swap zeroing leads to fstab pointing to non-existent swap UUID

### ISSUE THREAD

**Issue by javornikolov** [2creatives/vagrant-centos#8]
Current approach of zeroing the swap partition is problematic:
https://github.com/2creatives/vagrant-centos/blob/master/ks.cfg#L221

The result is something like that:

```
$ sudo swapon -s
Filename                Type        Size    Used    Priority
```

The problem is that fstab contains the UUID of this partition (not device name or something else). And that UUID is destroyed by `dd` and re-generated by `mkswap`.

I can imagine two options to handle that:
a) Use `seek` parameter of `dd` to skip zeroing the header of the partition. And do _not_ perform mkswap after that.
b) Save the original UUID before the maintenance and then re-use it in mkswap. (Or alternatively - change the UUID in fstab). I think UUID can be extracted with `blkid` or listing `/dev/disk/by-uuid`.

Another problem is that `dd` is executed with default block size which is terribly slow. It should be changed to e.g. 1MB. E.g.:
`dd if=/dev/zero of=/dev/sdb1 bs=1024k seek=1`

Another remark: maybe would be easier to manage the zeroing of free space and other operations too if using separate disk for swap. Also `/boot` partition is usually handy to have it in separate partition (in case of VM - easier to do that as separate disk).

**Comment by casr** [comment]
Thanks for the report! These are all very useful suggestions and the lack of swap is a pretty major oversight.

> Also /boot partition is usually handy to have it in separate partition (in case of VM - easier to do that as separate disk).

I'm curious about this. It does seem sensible but how have you found it handy?

**Comment by javornikolov** [comment]
> ```
> Also /boot partition is usually handy to have it in separate partition (in case of VM - easier to do that as separate disk).
> ```
> 
> I'm curious about this. It does seem sensible but how have you found it handy?

Maybe my bias comes from non-vm physical machines. With separate boot It's easier to change the file system or use LVM. One thing in my mind was eventually switching to btrfs file system (since it supports compression).

**Comment by casr** [comment]
I've opted to raise the swap size as per recommendations over at https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/s2-diskpartrecommend-ppc.html

I'm not going to put the /boot on a separate partition as it seems to complicate the setup without a much benefit. I can see it's use on less transient machines though so thanks for the tip!

**Comment by casr** [comment]
Thanks once again for the report!
